(executable
 (name ocamlmerlin_mlx)
 (package ocamlmerlin-mlx)
 (public_name ocamlmerlin-mlx)
 (modules ocamlmerlin_mlx)
 (flags
  :standard
  -open=Mlx_utils
  -open=Mlx_kernel
  -open=Mlx_ocaml_preprocess)
 (libraries
  mlx_ocaml_preprocess
  mlx_kernel
  mlx_conv
  merlin-lib.extend
  merlin-lib.kernel
  ppxlib))

(library
 (name mlx_conv)
 (package ocamlmerlin-mlx)
 (modules mlx_conv)
 (libraries mlx_ocaml_parsing merlin-lib.ocaml_parsing ppxlib))
